name: CI Pipeline

on:
  push:
    branches: [ "main", "dev" ]   # CI runs on push to main and dev
  pull_request:
    branches: [ "main", "dev" ]   # CI runs on PR to main and dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python with cache for dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      # Install dependencies and pytest with coverage support
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Run tests and generate coverage report
      - name: Run tests with coverage
        run: |
          python -m pytest tests/ --cov=app --cov-report=xml --cov-report=term-missing

      # Upload coverage report as an artifact in GitHub Actions
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./coverage.xml
